name = "Geferon's 1.21.1 Modpack"
author = "Geferon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70c3085649ffdc8bf587fad50bf890257981020a79e43f994f9f51cb447c1170"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
