name = "Geferon's 1.21.1 Modpack"
author = "Geferon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b44c2309a8ee5bcf94fc6b169768d6969d8a41c41195c6221b1765ec2757f19"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
