name = "Geferon's 1.21.1 Modpack"
author = "Geferon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61abaf37564fe515fe58cace7f8de6eef5a7270ae7fd32a4b3dec0a604dad8f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
