ServerEvents.recipes(allthemods => {
    // Crafting
    allthemods.remove({ id: 'railcraft:bronze_ingot_crafted_with_ingots'})
    allthemods.remove({ id: 'railcraft:invar_ingot_crafted_with_ingots'})
    allthemods.remove({ id: 'railcraft:brass_ingot_crafted_with_ingots'})
    allthemods.remove({ id: 'silentgear:bronze_ingot'})
    allthemods.remove({ id: 'modern_industrialization:materials/bronze_dust'})

    // Smelting
    allthemods.remove({ id: 'deeperdarker:coal_from_smelting_gloomslate_coal_ore'})
    allthemods.remove({ id: 'deeperdarker:coal_from_blasting_gloomslate_coal_ore'})
    allthemods.remove({ id: 'deeperdarker:iron_ingot_from_smelting_gloomslate_iron_ore'})
    allthemods.remove({ id: 'deeperdarker:iron_ingot_from_blasting_gloomslate_iron_ore'})
    allthemods.remove({ id: 'deeperdarker:copper_ingot_from_smelting_gloomslate_copper_ore'})
    allthemods.remove({ id: 'deeperdarker:copper_ingot_from_blasting_gloomslate_copper_ore'})
    allthemods.remove({ id: 'deeperdarker:gold_ingot_from_smelting_gloomslate_gold_ore'})
    allthemods.remove({ id: 'deeperdarker:gold_ingot_from_blasting_gloomslate_gold_ore'})
    allthemods.remove({ id: 'deeperdarker:redstone_from_smelting_gloomslate_redstone_ore'})
    allthemods.remove({ id: 'deeperdarker:redstone_from_blasting_gloomslate_redstone_ore'})
    allthemods.remove({ id: 'deeperdarker:emerald_from_smelting_gloomslate_emerald_ore'})
    allthemods.remove({ id: 'deeperdarker:emerald_from_blasting_gloomslate_emerald_ore'})
    allthemods.remove({ id: 'deeperdarker:lapis_lazuli_from_smelting_gloomslate_lapis_ore'})
    allthemods.remove({ id: 'deeperdarker:lapis_lazuli_from_blasting_gloomslate_lapis_ore'})
    allthemods.remove({ id: 'deeperdarker:diamond_from_smelting_gloomslate_diamond_ore'})
    allthemods.remove({ id: 'deeperdarker:diamond_from_blasting_gloomslate_diamond_ore'})
    allthemods.remove({ id: 'mekanism:processing/lead/ingot/from_ore_smelting'})
    allthemods.remove({ id: 'mekanism:processing/lead/ingot/from_ore_blasting'})
    allthemods.remove({ id: 'mekanism:processing/osmium/ingot/from_ore_smelting'})
    allthemods.remove({ id: 'mekanism:processing/osmium/ingot/from_ore_blasting'})
    allthemods.remove({ id: 'mekanism:processing/tin/ingot/from_ore_smelting'})
    allthemods.remove({ id: 'mekanism:processing/tin/ingot/from_ore_blasting'})
    allthemods.remove({ id: 'immersiveengineering:smelting/ingot_uranium'})
    allthemods.remove({ id: 'bigreactors:blasting/yellorium_from_ore'})
})